version: '3.8'

services:
  myfs:
    image: registry.cn-hangzhou.aliyuncs.com/pbx/myfs:latest
    container_name: myfs
    privileged: true
    # network_mode: "host"
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
      - "5060:5060/tcp"
      - "5080:5080/tcp"
      - "6060:6060/tcp"
      - "5061:5061/tcp"
      - "7443:7443/tcp"
      - "10000-10050:10000-10050/udp"
    stdin_open: true
    networks:
      - freeswitch_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8888:80"
      - "8448:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - myfs
    networks:
      - freeswitch_network
networks:
  freeswitch_network:
    driver: bridge